# Generated by Django 6.0.3 on 2026-04-02 21:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# soda_mixer.flavors.migrations.0002_popular_flavors

def create_popular_flavors(apps, schema_editor):
    """Create initial popular SodaStream flavors."""
    Flavor = apps.get_model('flavors', 'Flavor')
    
    popular_flavors = [
        # Citrus - Intensity 2-3
        ('Lemon Lime', 'citrus', 3, 'Zesty lemon with a hint of lime', 'citrus, lemon, lime, zesty'),
        ('Orange', 'citrus', 2, 'Classic bright orange flavor', 'citrus, orange, sweet'),
        ('Grapefruit Pink', 'citrus', 3, 'Tart and refreshing pink grapefruit', 'citrus, grapefruit, tart, tangy'),
        ('Lime', 'citrus', 2, 'Fresh and crisp lime', 'citrus, lime, tart'),
        
        # Berry - Intensity 3-4
        ('Blackberry', 'berry', 3, 'Rich blackberry flavor', 'berry, blackberry, sweet, tart'),
        ('Cranberry', 'berry', 4, 'Tart and tangy cranberry', 'berry, cranberry, tart, zesty'),
        ('Wild Blueberry', 'berry', 2, 'Sweet blueberry with wild hints', 'berry, blueberry, sweet'),
        ('Strawberry', 'berry', 2, 'Classic sweet strawberry', 'berry, strawberry, sweet'),
        ('Raspberry', 'berry', 3, 'Tart raspberry flavor', 'berry, raspberry, tart'),
        ('Mixed Berry', 'berry', 2, 'Blend of seasonal berries', 'berry, mixed, sweet'),
        
        # Tropical - Intensity 2-3
        ('Coconut', 'tropical', 2, 'Smooth tropical coconut', 'tropical, coconut, creamy, sweet'),
        ('Pineapple', 'tropical', 3, 'Tangy tropical pineapple', 'tropical, pineapple, sweet, tart'),
        ('Mango', 'tropical', 2, 'Sweet and creamy mango', 'tropical, mango, sweet, creamy'),
        ('Passion Fruit', 'tropical', 4, 'Exotic passion fruit tang', 'tropical, passion, tart, exotic'),
        
        # Herbal - Intensity 1-3
        ('Cucumber', 'herbal', 2, 'Refreshing cucumber with mint', 'herbal, cucumber, fresh, mint'),
        ('Mint', 'herbal', 3, 'Cool refreshing mint', 'herbal, mint, cool, fresh'),
        
        # Sweet - Intensity 2-4
        ('Vanilla', 'sweet', 1, 'Creamy smooth vanilla', 'sweet, vanilla, creamy'),
        ('Caramel Apple', 'sweet', 3, 'Sweet caramel with apple notes', 'sweet, caramel, apple'),
        
        # Sour - Intensity 4-5
        ('Green Apple', 'sour', 4, 'Tart green apple punch', 'sour, apple, tart, tangy'),
    ]
    
    for name, category, intensity, description, flavor_notes in popular_flavors:
        Flavor.objects.create(
            name=name,
            category=category,
            intensity=intensity,
            description=description,
            flavor_notes=flavor_notes
        )


class Migration(migrations.Migration):

    replaces = [('flavors', '0001_initial'), ('flavors', '0002_popular_flavors'), ('flavors', '0003_recipecategory_mixhistory_mixhistoryflavor_and_more'), ('flavors', '0004_ingredient_remove_recipeflavor_flavor_and_more'), ('flavors', '0005_alter_mixhistoryingredient_ingredient_and_more'), ('flavors', '0006_alter_mixhistory_drink_type_alter_recipe_drink_type'), ('flavors', '0007_systemconfiguration'), ('flavors', '0008_alter_ingredient_category')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('citrus', 'Citrus'), ('berry', 'Berry'), ('tropical', 'Tropical'), ('herbal', 'Herbal'), ('spice', 'Spice'), ('sweet', 'Sweet'), ('sour', 'Sour'), ('artificial', 'Artificial/Fun')], default='citrus', max_length=20)),
                ('intensity', models.IntegerField(default=3, help_text='Intensity level from 1 (mild) to 5 (strong)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sweetness', models.IntegerField(default=3, help_text='Sweetness level from 1 (low) to 5 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('acidity', models.IntegerField(default=3, help_text='Acidity/tartness level from 1 (low) to 5 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('bitterness', models.IntegerField(default=1, help_text='Bitterness level from 1 (low) to 5 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_in_inventory', models.BooleanField(default=True, help_text='Whether this flavor is currently in your bar/inventory')),
                ('description', models.TextField(blank=True, null=True)),
                ('flavor_notes', models.CharField(blank=True, help_text="Comma-separated flavor descriptors (e.g., 'citrus, sweet, tart')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Flavors',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0, help_text='User rating from 0 to 5 stars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proportion_ml', models.FloatField(default=1.0, help_text='Amount of flavor in milliliters')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flavors.flavor')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_flavors', to='flavors.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'flavor')},
            },
        ),
        migrations.RunPython(
            code=create_popular_flavors,
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(choices=[('bg-primary', 'Blue'), ('bg-success', 'Green'), ('bg-danger', 'Red'), ('bg-warning text-dark', 'Yellow'), ('bg-info text-dark', 'Cyan'), ('bg-secondary', 'Grey'), ('bg-dark', 'Dark'), ('bg-pink', 'Pink')], default='bg-secondary', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Recipe Categories',
            },
        ),
        migrations.CreateModel(
            name='MixHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mixed_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_recipe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entry', to='flavors.recipe')),
            ],
            options={
                'verbose_name_plural': 'Mix History',
                'ordering': ['-mixed_at'],
            },
        ),
        migrations.CreateModel(
            name='MixHistoryFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proportion_ml', models.FloatField(default=1.0)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flavors.flavor')),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_flavors', to='flavors.mixhistory')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='flavors.recipecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeflavor',
            unique_together=None,
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ingredient_type', models.CharField(choices=[('SODA_SYRUP', 'Soda Syrup'), ('COFFEE_BEAN', 'Coffee Bean'), ('ADDITIVE', 'Additive (e.g., Creamer, Sugar)'), ('OTHER', 'Other')], default='SODA_SYRUP', max_length=20)),
                ('category', models.CharField(choices=[('citrus', 'Citrus'), ('berry', 'Berry'), ('tropical', 'Tropical'), ('herbal', 'Herbal'), ('spice', 'Spice'), ('sweet', 'Sweet'), ('sour', 'Sour'), ('artificial', 'Artificial/Fun'), ('coffee', 'Coffee Profile')], default='citrus', max_length=20)),
                ('intensity', models.IntegerField(default=3, help_text='Intensity level from 1 (mild) to 5 (strong)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sweetness', models.IntegerField(default=3, help_text='Sweetness level from 1 (low) to 5 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('acidity', models.IntegerField(default=3, help_text='Acidity/tartness level from 1 (low) to 5 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('bitterness', models.IntegerField(default=1, help_text='Bitterness level from 1 (low) to 5 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('roast_level', models.IntegerField(blank=True, help_text='Roast level from 1 (light) to 5 (dark)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('process', models.CharField(blank=True, choices=[('washed', 'Washed'), ('natural', 'Natural'), ('honey', 'Honey'), ('other', 'Other')], max_length=50, null=True)),
                ('roaster', models.CharField(blank=True, max_length=100, null=True)),
                ('is_in_inventory', models.BooleanField(default=True, help_text='Whether this ingredient is currently in your bar/lab')),
                ('description', models.TextField(blank=True, null=True)),
                ('flavor_notes', models.CharField(blank=True, help_text="Comma-separated flavor descriptors (e.g., 'berry, chocolatey, floral')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.RemoveField(
            model_name='recipeflavor',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='mixhistoryflavor',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='mixhistoryflavor',
            name='mix',
        ),
        migrations.RemoveField(
            model_name='recipeflavor',
            name='recipe',
        ),
        migrations.AddField(
            model_name='mixhistory',
            name='drink_type',
            field=models.CharField(choices=[('SODA', 'Soda Synthesis'), ('COFFEE', 'Coffee Laboratory')], default='SODA', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='brew_method',
            field=models.CharField(blank=True, choices=[('espresso', 'Espresso'), ('v60', 'V60 Pour Over'), ('chemex', 'Chemex'), ('french_press', 'French Press'), ('aeropress', 'AeroPress'), ('cold_brew', 'Cold Brew'), ('machine', 'Automatic Machine'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='brew_time_sec',
            field=models.IntegerField(blank=True, help_text='Total brew time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='drink_type',
            field=models.CharField(choices=[('SODA', 'Soda Synthesis'), ('COFFEE', 'Coffee Laboratory')], default='SODA', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='grind_size',
            field=models.CharField(blank=True, choices=[('fine', 'Fine'), ('medium', 'Medium'), ('coarse', 'Coarse')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_water_g',
            field=models.FloatField(blank=True, help_text='Total water used in grams', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='water_temp_c',
            field=models.FloatField(blank=True, help_text='Water temperature in Celsius', null=True),
        ),
        migrations.CreateModel(
            name='MixHistoryIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1.0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flavors.ingredient')),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_ingredients', to='flavors.mixhistory')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1.0, help_text='Amount (ml for Soda, grams for Coffee)')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flavors.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='flavors.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.DeleteModel(
            name='MixHistoryFlavor',
        ),
        migrations.DeleteModel(
            name='RecipeFlavor',
        ),
        migrations.AlterField(
            model_name='mixhistoryingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_usage', to='flavors.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_usage', to='flavors.ingredient'),
        ),
        migrations.AlterField(
            model_name='mixhistory',
            name='drink_type',
            field=models.CharField(choices=[('SODA', 'Soda Synthesis'), ('COFFEE', 'Coffee Laboratory'), ('SLUSHIE', 'Cryo-Slushie Lab')], default='SODA', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='drink_type',
            field=models.CharField(choices=[('SODA', 'Soda Synthesis'), ('COFFEE', 'Coffee Laboratory'), ('SLUSHIE', 'Cryo-Slushie Lab')], default='SODA', max_length=10),
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealie_url', models.URLField(blank=True, help_text='The base URL of your Mealie instance (e.g., https://mealie.local)')),
                ('mealie_api_key', models.CharField(blank=True, help_text='Long-lived API token generated in Mealie User Settings', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(default='citrus', max_length=50),
        ),
    ]
