# Generated by Django 6.0.3 on 2026-04-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='compatible_systems',
            field=models.CharField(default='SODA,COFFEE,SLUSHIE', help_text='Comma-separated list of compatible lab systems (SODA, COFFEE, SLUSHIE)', max_length=100),
        ),
    ]
