# Generated by Django 6.0.3 on 2026-04-07 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0002_ingredient_compatible_systems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixhistoryingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mix_usage', to='flavors.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_usage', to='flavors.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='mixhistoryingredient',
            unique_together={('mix', 'ingredient')},
        ),
    ]
