# Generated by Django 6.0.3 on 2026-04-20 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0004_mixhistoryingredient_acidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='complexity',
            field=models.IntegerField(default=3, help_text='Complexity of flavor profile from 1 (simple) to 5 (layered/deep)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='mixhistoryingredient',
            name='complexity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='complexity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
